# Generated by Django 4.0.4 on 2022-04-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_profile_is_private_page_searchhostory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_private_page',
        ),
        migrations.CreateModel(
            name='TwoFactorAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است ؟')),
                ('text_message', models.CharField(max_length=20, verbose_name='کد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ورود دو مرحله ای',
                'verbose_name_plural': 'ورود دو مرحله ای',
            },
        ),
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private_page', models.BooleanField(default=False, verbose_name='آیا پیج خصوصی است ؟')),
                ('show_activity_status', models.BooleanField(default=False, verbose_name='نشان دادن وضیعت فعال بودن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات حساب',
                'verbose_name_plural': 'تنظیمات حساب',
            },
        ),
    ]
