# Generated by Django 4.0.4 on 2022-04-16 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedExtensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_allowed', models.CharField(max_length=20, verbose_name='فایل مجاز')),
            ],
            options={
                'verbose_name': 'فرمت های مجاز فایل ها',
                'verbose_name_plural': 'فرمت های مجاز فایل ها',
            },
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(verbose_name='متن')),
                ('is_multi_slide', models.BooleanField(default=False, verbose_name='آیا چند اسلایدی است ؟')),
                ('image_or_video', models.FileField(upload_to='PostImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[''], message='فرمت فایل وارد شده مجاز نیست')], verbose_name='فایل چند رسانه ای')),
                ('hashtags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.hashtag', verbose_name='برچسب')),
                ('location_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.locationtag', verbose_name='مکان')),
                ('tagged_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertagged', to=settings.AUTH_USER_MODEL, verbose_name='کاربران تگ شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پسند پست',
                'verbose_name_plural': 'پسند پست',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_header', models.BooleanField(default=False, verbose_name='آیا سر گروه است ؟')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('commented_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.postcomment', verbose_name='سر گروه')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظرات پست',
                'verbose_name_plural': 'نظرات پست',
            },
        ),
    ]
