# Generated by Django 4.0.4 on 2022-04-16 16:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_or_video',
            field=models.FileField(upload_to='PostImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=[], message='فرمت فایل وارد شده مجاز نیست')], verbose_name='فایل چند رسانه ای'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postcomment', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پسند نظرات',
                'verbose_name_plural': 'پسند نظرات',
            },
        ),
    ]
