# Generated by Django 4.0.4 on 2022-04-16 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_publish_date_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.hashtag', verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_or_video',
            field=models.FileField(upload_to='PostImages', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg'], message='فرمت فایل وارد شده مجاز نیست')], verbose_name='فایل چند رسانه ای'),
        ),
    ]
