# Generated by Django 4.0.4 on 2022-04-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_postlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsave',
            name='saved_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ثبت'),
        ),
    ]
