# Generated by Django 4.0.4 on 2022-04-18 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ارسال')),
                ('message_text', models.TextField(null=True)),
                ('media', models.FileField(null=True, upload_to='DirectMedias', verbose_name='فایل')),
                ('seen_state', models.BooleanField(default=False, verbose_name='مشاهده شده ؟')),
                ('send_state', models.BooleanField(default=False, verbose_name='ارسال شده ؟')),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreciver', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersneder', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
