# Generated by Django 4.0.4 on 2022-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='DirectMedias', verbose_name='فایل'),
        ),
    ]
