# Generated by Django 4.0.4 on 2022-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='نام سایت شما')),
                ('logo', models.FileField(upload_to='SiteMedias', verbose_name='فایل لوگو')),
                ('domainname', models.URLField(verbose_name='آدرس سایت')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
