# Generated by Django 4.0.4 on 2022-04-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_address', models.CharField(choices=[('likes', 'لایک'), ('comment', 'نظر'), ('follow', 'فالو'), ('unfollow', 'آنفالو')], max_length=200, verbose_name='آدرس ارسال درخواست')),
                ('request_count', models.SmallIntegerField(default=0, verbose_name='تعداد درخواست')),
                ('limit_type', models.CharField(choices=[('block for ever', 'محدودیت همیشگی'), ('block one week', 'محدودیت یک هفته ای'), ('block one month', 'محدودیت یک ماه'), ('block one year', 'محدودیت یک سال'), ('block a day', 'محدودیت یک روزه'), ('block one hour', 'محدودیت یک روزه')], max_length=200, verbose_name='نوع محدودیت')),
            ],
            options={
                'verbose_name': 'قوانین محدودیت',
                'verbose_name_plural': 'قوانین محدودیت',
            },
        ),
    ]
